name: Update Heatmap

on: workflow_dispatch

jobs:
  update_heatmap:
    name: Update Heatmap
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Scripts
        run: |
          jupyter nbconvert --to script summary.ipynb
          python summary.py
      
      - name: Commit and Push Changes
        run: |
          git config --global user.name "${{ github.actor }}$"
          git config --global user.email "$alive.vb.s2@gmail.com"
          git add nikkei_chart.png heatmap.png
          git commit -m "Update on `date` with GitHub Actions"
          git push origin main
